

"use client";

import React, { Suspense } from 'react';
import { useSearchParams, useRouter, usePathname } from 'next/navigation';
import { doc, getDoc } from 'firebase/firestore';
import { db } from '@/lib/firebase';
import { Button } from '@/components/ui/button';
import { Loader2, ArrowLeft, XCircle, Phone, MapPin, Mail } from 'lucide-react';
import Image from 'next/image';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { AuthGuard } from '@/hooks/use-auth';


interface BookingData {
  id: string;
  customerName?: string;
  customerPhone?: string;
  customerEmail?: string;
  plateNumber?: string;
  carMake?: string;
  carModel?: string;
  policyNumber?: string;
  authorisedBy?: string;
  createdAt?: any;
  bookingNumber?: string;
  branch?: string; 
  comments?: string;
  insurerName?: string;
  status?: string;
  rejectionReason?: string;
}

interface ReportState {
  booking: BookingData | null;
  loading: boolean;
}

class ReportToPrint extends React.Component<{booking: BookingData | null}> {
  render() {
    const { booking } = this.props;

    if (!booking) {
      return <div className="text-center py-12 font-semibold text-lg">Booking not found.</div>;
    }

    return (
        <div className="bg-white shadow-2xl rounded-lg flex flex-col">
            <header className="relative p-2 flex items-start gap-4 border-b-4 border-orange-400">
                <div className="flex-shrink-0">
                    <Image src="/logo.jpeg" alt="Sonic Motor Valuers Logo" width={140} height={140} className="object-contain" />
                </div>
                <div className="flex-grow text-center">
                    <h2 className="font-bold text-3xl text-red-800">SONIC MOTOR VALUERS AND ASSESSORS LTD</h2>
                    <p className="text-sm font-semibold mt-1">
                        Dealer in: Valuation and Assessment for Bank Loan Facilities, Motor Vehicles Buying & Selling, Court Bonds,
                        Inventories, Insurance purposes and Accident Assessment etc.
                    </p>
                </div>
            </header>

            <main className="flex-grow p-14 watermarked">
             <div className="report-content">
              <h2 className="text-3xl font-bold text-center text-black uppercase tracking-widest mb-4">
                Assessment Authorization Letter
              </h2>
              <p className="text-lg text-center text-gray-600 mb-8">
                The following authorization letter has been generated by Sonic Motor Valuers for {booking.insurerName}
              </p>

              {booking.status === 'Rejected' && (
                <Alert variant="destructive" className="mb-8">
                    <XCircle className="h-4 w-4" />
                    <AlertTitle>Booking Rejected by Admin</AlertTitle>
                    <AlertDescription>
                       <strong>Reason:</strong> {booking.rejectionReason || "This booking was rejected."}
                    </AlertDescription>
                </Alert>
              )}
              
              <div className="bg-gray-50 border border-gray-200 rounded-lg p-6 mb-8">
                <h3 className="text-2xl font-semibold text-black mb-4">Booking Details</h3>
                <div className="grid grid-cols-2 gap-x-12 gap-y-4 text-lg">
                    <div className="flex justify-between py-2 border-b border-gray-100">
                        <span className="font-semibold text-gray-700">Client Name:</span>
                        <span className="text-gray-900 font-medium">{booking.customerName}</span>
                    </div>
                    <div className="flex justify-between py-2 border-b border-gray-100">
                        <span className="font-semibold text-gray-700">Vehicle:</span>
                        <span className="text-gray-900 font-medium">{`${booking.carMake} ${booking.carModel}`}</span>
                    </div>
                    <div className="flex justify-between py-2 border-b border-gray-100">
                        <span className="font-semibold text-gray-700">Phone Number:</span>
                        <span className="text-gray-900 font-medium">{booking.customerPhone}</span>
                    </div>
                    <div className="flex justify-between py-2 border-b border-gray-100">
                        <span className="font-semibold text-gray-700">Registration No:</span>
                        <span className="text-gray-900 font-medium">{booking.plateNumber}</span>
                    </div>
                    <div className="flex justify-between py-2 border-b border-gray-100">
                        <span className="font-semibold text-gray-700">Email Address:</span>
                        <span className="text-gray-900 font-medium">{booking.customerEmail}</span>
                    </div>
                    <div className="flex justify-between py-2 border-b border-gray-100">
                        <span className="font-semibold text-gray-700">Policy Number:</span>
                        <span className="text-gray-900 font-medium">{booking.policyNumber}</span>
                    </div>
                    <div className="flex justify-between py-2 border-b border-gray-100">
                        <span className="font-semibold text-gray-700">Authorised By (Agent):</span>
                        <span className="text-gray-900 font-medium">{booking.authorisedBy}</span>
                    </div>
                    <div className="flex justify-between py-2 border-b border-gray-100">
                        <span className="font-semibold text-gray-700">Date Issued:</span>
                        <span className="text-gray-900 font-medium">{booking.createdAt ? new Date(booking.createdAt.seconds * 1000).toLocaleDateString() : 'N/A'}</span>
                    </div>
                    <div className="flex justify-between py-2 border-b border-gray-100">
                        <span className="font-semibold text-gray-700">Reference No:</span>
                        <span className="text-gray-900 font-medium">{booking.bookingNumber}</span>
                    </div>
                    <div className="flex justify-between py-2 border-b border-gray-100">
                        <span className="font-semibold text-gray-700">Branch:</span>
                        <span className="text-gray-900 font-medium">{booking.branch}</span>
                    </div>
                    <div className="flex justify-between py-2 border-b border-gray-100 col-span-2">
                        <span className="font-semibold text-gray-700">Comments:</span>
                        <span className="text-gray-900 font-medium text-right">{booking.comments || 'N/A'}</span>
                    </div>
                </div>
              </div>

              <div className="mt-12 pt-6 border-t-2 border-dashed border-gray-300">
                  <h3 className="font-bold text-xl text-black mb-3">NOTE TO INSURED</h3>
                  <p className="text-lg text-gray-700 mb-4">
                      Please ensure to avail the following documents at the time of valuation, in the absence of which the exercise cannot be completed:
                  </p>
                  <ol className="list-decimal list-inside text-lg text-gray-700 space-y-2 pl-4">
                      <li>Copy of Logbook/Importation Documents</li>
                      <li>Copy of PIN certificate</li>
                      <li>Copy of ID or Passport</li>
                      <li>Copy of incorporation for corporate clients</li>
                  </ol>
              </div>

              <div className="mt-10 pt-6 border-t-2 border-dashed border-gray-300">
                  <p className="text-lg font-semibold text-red-600">
                      For Guarantor purpose only: <span className="font-normal text-gray-700">Please note that cover will revert to third party only if the vehicle is not valued within 14 days of cover inception.</span>
                  </p>
              </div>
            </div>
            </main>
             <footer className="bg-white p-1 text-black text-xs mt-auto border-t-4 border-orange-400">
                <div className="max-w-5xl mx-auto text-center">
                    <p className="font-bold text-blue-800">Location: Plessy Hse, next to Highway Mall & Carrefour Mega, along Uhuru Highway.</p>
                    <p className="font-bold text-green-700">P.O. Box 103-90200, Nairobi. Mob: 0798662206/0750677839</p>
                </div>
            </footer>
        </div>
    );
  }
}

class BookingReportPageContent extends React.Component<{ router: any; searchParams: any; pathname: string; }, ReportState> {
  constructor(props: { router: any; searchParams: any; pathname: string; }) {
    super(props);
    this.state = {
      booking: null,
      loading: true,
    };
  }

  componentDidMount() {
    const bookingId = this.props.searchParams.get('id');

    if (bookingId) {
      const fetchBooking = async () => {
        this.setState({ loading: true });
        const docRef = doc(db, 'bookings', bookingId as string);
        const docSnap = await getDoc(docRef);

        if (docSnap.exists()) {
          const bookingData = { id: docSnap.id, ...docSnap.data() } as BookingData;
          this.setState({ booking: bookingData });
          if (bookingData.plateNumber && bookingData.bookingNumber) {
            document.title = `${bookingData.plateNumber} - ${bookingData.bookingNumber}`;
          }
        } else {
          console.log('No such document!');
        }
        this.setState({ loading: false });
      };

      fetchBooking();
    }
  }

  handleGoBack = () => {
    const isAdmin = this.props.pathname.includes('/admin/');
    const destination = isAdmin ? '/admin/dashboard' : '/client/dashboard';
    this.props.router.push(destination);
  };

  render() {
    if (this.state.loading) {
      return (
        <div className="flex justify-center items-center h-screen bg-gray-100">
          <Loader2 className="h-10 w-10 animate-spin text-primary" />
        </div>
      );
    }
    
    return (
      <div className="bg-gray-200 min-h-screen p-4 sm:p-8 font-sans print:bg-white print:p-0">
        <div className="max-w-5xl mx-auto">
          <div className="flex justify-end mb-6 gap-4 print:hidden">
            <Button onClick={() => window.print()} variant="default">
                Print / Save PDF
            </Button>
            <Button onClick={this.handleGoBack} variant="outline" className="text-black border-black hover:bg-black hover:text-white">
              <ArrowLeft className="mr-2 h-5 w-5" />
              Go Back
            </Button>
          </div>
          <ReportToPrint booking={this.state.booking} />
        </div>
      </div>
    );
  }
}

function BookingReportWrapper() {
    const router = useRouter();
    const searchParams = useSearchParams();
    const pathname = usePathname();
    return <BookingReportPageContent router={router} searchParams={searchParams} pathname={pathname} />;
}

const GuardedBookingReportPage = AuthGuard(BookingReportWrapper, { allowClients: true });


export default function BookingReportPage() {
  return (
    <Suspense fallback={
        <div className="flex justify-center items-center h-screen bg-gray-100">
            <Loader2 className="h-10 w-10 animate-spin text-primary" />
        </div>
    }>
        <GuardedBookingReportPage />
    </Suspense>
  );
}
