
"use client";

import React, { useEffect, useState } from 'react';
import { doc, getDoc } from 'firebase/firestore';
import { db } from '@/lib/firebase';
import { Loader2 } from 'lucide-react';
import Image from 'next/image';

interface BookingData {
  id: string;
  customerName?: string;
  customerPhone?: string;
  customerEmail?: string;
  plateNumber?: string;
  carMake?: string;
  carModel?: string;
  policyNumber?: string;
  authorisedBy?: string;
  createdAt?: any;
  bookingNumber?: string;
  branch?: string; 
  comments?: string;
  insurerName?: string;
}

class ReportToPrint extends React.Component<{ booking: BookingData | null }> {
  render() {
    const { booking } = this.props;
    if (!booking) return null;

    return (
      <div className="bg-white p-14 shadow-lg rounded-lg" id="report">
        <header className="flex justify-between items-center pb-6 border-b-2 border-primary">
          <div>
            <Image src="/logo.jpeg" alt="Company Logo" width={200} height={80} />
          </div>
          <div className="text-left">
            <h1 className="text-4xl font-extrabold text-black">Sonic Motor Valuers</h1>
            <p className="text-base text-gray-700 mt-1">
              Highway Mall, Uhuru Highway<br />
              Nairobi, Kenya
            </p>
          </div>
          <div className="text-right text-base text-gray-700">
            <p><span className="font-semibold">Phone:</span> +254 712 345 678</p>
            <p><span className="font-semibold">Email:</span> casamotorvaluer@gmail.com</p>
          </div>
        </header>

        <main className="mt-10">
          <h2 className="text-2xl font-bold text-center text-black uppercase tracking-widest mb-4">
            Assessment Authorization Letter
          </h2>
          <p className="text-base text-center text-gray-600 mb-8">
            The following authorization letter has been generated by Sonic Motor Valuers for {booking.insurerName}
          </p>
          
          <div className="bg-gray-50 border border-gray-200 rounded-lg p-6 mb-8">
            <h3 className="text-xl font-semibold text-black mb-4">Booking Details</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-x-12 gap-y-4 text-base">
                <div className="flex justify-between py-2 border-b border-gray-100">
                    <span className="font-semibold text-gray-700">Client Name:</span>
                    <span className="text-gray-900 font-medium">{booking.customerName}</span>
                </div>
                <div className="flex justify-between py-2 border-b border-gray-100">
                    <span className="font-semibold text-gray-700">Vehicle:</span>
                    <span className="text-gray-900 font-medium">{`${booking.carMake} ${booking.carModel}`}</span>
                </div>
                <div className="flex justify-between py-2 border-b border-gray-100">
                    <span className="font-semibold text-gray-700">Phone Number:</span>
                    <span className="text-gray-900 font-medium">{booking.customerPhone}</span>
                </div>
                <div className="flex justify-between py-2 border-b border-gray-100">
                    <span className="font-semibold text-gray-700">Registration No:</span>
                    <span className="text-gray-900 font-medium">{booking.plateNumber}</span>
                </div>
                <div className="flex justify-between py-2 border-b border-gray-100">
                    <span className="font-semibold text-gray-700">Email Address:</span>
                    <span className="text-gray-900 font-medium">{booking.customerEmail}</span>
                </div>
                <div className="flex justify-between py-2 border-b border-gray-100">
                    <span className="font-semibold text-gray-700">Policy Number:</span>
                    <span className="text-gray-900 font-medium">{booking.policyNumber}</span>
                </div>
                <div className="flex justify-between py-2 border-b border-gray-100">
                    <span className="font-semibold text-gray-700">Authorised By:</span>
                    <span className="text-gray-900 font-medium">{booking.authorisedBy}</span>
                </div>
                <div className="flex justify-between py-2 border-b border-gray-100">
                    <span className="font-semibold text-gray-700">Date Issued:</span>
                    <span className="text-gray-900 font-medium">{booking.createdAt ? new Date(booking.createdAt.seconds * 1000).toLocaleDateString() : 'N/A'}</span>
                </div>
                <div className="flex justify-between py-2 border-b border-gray-100">
                    <span className="font-semibold text-gray-700">Reference No:</span>
                    <span className="text-gray-900 font-medium">{booking.bookingNumber}</span>
                </div>
                <div className="flex justify-between py-2 border-b border-gray-100">
                    <span className="font-semibold text-gray-700">Branch:</span>
                    <span className="text-gray-900 font-medium">{booking.branch}</span>
                </div>
                <div className="flex justify-between py-2 border-b border-gray-100 col-span-1 md:col-span-2">
                    <span className="font-semibold text-gray-700">Comments:</span>
                    <span className="text-gray-900 font-medium text-right">{booking.comments || 'N/A'}</span>
                </div>
            </div>
          </div>

          <div className="mt-12 pt-6 border-t-2 border-dashed border-gray-300">
              <h3 className="font-bold text-lg text-black mb-3">NOTE TO INSURED</h3>
              <p className="text-base text-gray-700 mb-4">
                  Please ensure to avail the following documents at the time of valuation, in the absence of which the exercise cannot be completed:
              </p>
              <ol className="list-decimal list-inside text-base text-gray-700 space-y-2 pl-4">
                  <li>Copy of Logbook/Importation Documents</li>
                  <li>Copy of PIN certificate</li>
                  <li>Copy of ID or Passport</li>
                  <li>Copy of incorporation for corporate clients</li>
              </ol>
          </div>

          <div className="mt-10 pt-6 border-t-2 border-dashed border-gray-300">
              <p className="text-base font-semibold text-red-600">
                  For insurance purpose only: <span className="font-normal text-gray-700">Please note that cover will revert to third party only if the vehicle is not valued within 14 days of cover inception.</span>
              </p>
          </div>
        </main>

      </div>
    );
  }
}

export default function BookingReport({ bookingId }: { bookingId: string }) {
  const [booking, setBooking] = useState<BookingData | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (bookingId) {
      const fetchBooking = async () => {
        setLoading(true);
        const docRef = doc(db, 'bookings', bookingId as string);
        const docSnap = await getDoc(docRef);

        if (docSnap.exists()) {
          setBooking({ id: docSnap.id, ...docSnap.data() } as BookingData);
        } else {
          console.log('No such document!');
        }
        setLoading(false);
      };

      fetchBooking();
    }
  }, [bookingId]);

  if (loading) {
    return (
      <div className="flex justify-center items-center h-96 bg-gray-100">
        <Loader2 className="h-10 w-10 animate-spin text-primary" />
      </div>
    );
  }

  if (!booking) {
    return <div className="text-center py-12 font-semibold text-lg">Booking not found.</div>;
  }

  return (
    <div className="bg-gray-100 font-sans">
       <div className="max-w-5xl mx-auto">
        <div>
            <ReportToPrint booking={booking}/>
