
"use client";

import { useEffect, useState, useRef } from 'react';
import { useSearchParams } from 'next/navigation';
import { doc, getDoc } from 'firebase/firestore';
import { db } from '@/lib/firebase';
import { Button } from '@/components/ui/button';
import { Loader2, Printer } from 'lucide-react';
import { useReactToPrint } from 'react-to-print';
import Image from 'next/image';

interface BookingData {
  id: string;
  customerName?: string;
  customerPhone?: string;
  plateNumber?: string;
  policyNumber?: string;
  authorisedBy?: string;
  createdAt?: any;
  bookingNumber?: string;
  branch?: string; 
  comments?: string;
}

export default function BookingReport() {
  const searchParams = useSearchParams();
  const bookingId = searchParams.get('id');
  const [booking, setBooking] = useState<BookingData | null>(null);
  const [loading, setLoading] = useState(true);
  const componentRef = useRef(null);

  const handlePrint = useReactToPrint({
    content: () => componentRef.current,
    documentTitle: `Assessment_Authorization_Letter_${booking?.bookingNumber}`,
  });

  useEffect(() => {
    if (bookingId) {
      const fetchBooking = async () => {
        setLoading(true);
        const docRef = doc(db, 'bookings', bookingId as string);
        const docSnap = await getDoc(docRef);

        if (docSnap.exists()) {
          setBooking({ id: docSnap.id, ...docSnap.data() } as BookingData);
        } else {
          console.log('No such document!');
        }
        setLoading(false);
      };

      fetchBooking();
    }
  }, [bookingId]);

  if (loading) {
    return (
      <div className="flex justify-center items-center h-screen">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    );
  }

  if (!booking) {
    return <div className="text-center py-10">Booking not found.</div>;
  }

  return (
    <div className="bg-gray-100 min-h-screen p-4 sm:p-8">
       <div className="max-w-4xl mx-auto">
        <div className="flex justify-end mb-4 gap-2">
            <Button onClick={handlePrint} variant="outline">
                <Printer className="mr-2 h-4 w-4" />
                Print / Save PDF
            </Button>
        </div>
        <div ref={componentRef} className="bg-white p-8 sm:p-12 shadow-lg" id="report">
          <header className="flex justify-between items-start pb-4 border-b border-gray-300">
            <div className="text-left">
              <h1 className="text-2xl sm:text-3xl font-bold text-gray-800">CASA Motor Valuers & Assessors</h1>
              <p className="text-sm text-gray-600">
                Highway Mall, Uhuru Highway<br />
                Nairobi, Kenya
              </p>
            </div>
            <div className="text-right text-sm text-gray-600">
              <p>Phone: +254 712 345 678</p>
              <p>Email: casamotorvaluer@gmail.com</p>
            </div>
          </header>

          <main className="mt-8">
            <h2 className="text-xl font-semibold text-center uppercase tracking-wider mb-4">
              Assessment Authorization Letter
            </h2>
            <p className="text-sm mb-6">
              The following authorization letter has been generated by CASA Motor Valuers and Assessors LTD on behalf of THE MONARCH INS. CO. LTD
            </p>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-12 gap-y-4 text-sm">
                <div className="flex justify-between border-b py-2">
                    <span className="font-semibold text-gray-600">Client Name</span>
                    <span className="text-gray-800">{booking.customerName}</span>
                </div>
                <div className="flex justify-between border-b py-2">
                    <span className="font-semibold text-gray-600">Phone Number</span>
                    <span className="text-gray-800">{booking.customerPhone}</span>
                </div>
                <div className="flex justify-between border-b py-2">
                    <span className="font-semibold text-gray-600">Registration Number</span>
                    <span className="text-gray-800">{booking.plateNumber}</span>
                </div>
                 <div className="flex justify-between border-b py-2">
                    <span className="font-semibold text-gray-600">Policy Number</span>
                    <span className="text-gray-800">{booking.policyNumber}</span>
                </div>
                <div className="flex justify-between border-b py-2">
                    <span className="font-semibold text-gray-600">Authorised By</span>
                    <span className="text-gray-800">{booking.authorisedBy}</span>
                </div>
                <div className="flex justify-between border-b py-2">
                    <span className="font-semibold text-gray-600">Added On</span>
                    <span className="text-gray-800">{booking.createdAt ? new Date(booking.createdAt.seconds * 1000).toLocaleDateString() : 'N/A'}</span>
                </div>
                 <div className="flex justify-between border-b py-2">
                    <span className="font-semibold text-gray-600">Authorization Ref No</span>
                    <span className="text-gray-800">{booking.bookingNumber}</span>
                </div>
                 <div className="flex justify-between border-b py-2">
                    <span className="font-semibold text-gray-600">Broker</span>
                    <span className="text-gray-800">{booking.branch}</span>
                </div>
                 <div className="flex justify-between border-b py-2 col-span-1 sm:col-span-2">
                    <span className="font-semibold text-gray-600">Comments</span>
                    <span className="text-gray-800 text-right">{booking.comments || 'N/A'}</span>
                </div>
            </div>

            <div className="mt-10 pt-6 border-t border-dashed">
                <h3 className="font-bold text-gray-700 mb-2">NOTE TO INSURED</h3>
                <p className="text-sm text-gray-600 mb-4">
                    Please ensure to avail the following documents at the time of valuation in the absence of which the exercise cannot be completed:
                </p>
                <ol className="list-decimal list-inside text-sm text-gray-600 space-y-1">
                    <li>Copy of Logbook/Importation Documents</li>
                    <li>Copy of pin certificate</li>
                    <li>Copy of ID or Passport</li>
                    <li>Copy of incorporation for corporate clients</li>
                </ol>
            </div>

            <div className="mt-8 pt-4 border-t border-gray-200">
                <p className="text-sm font-semibold text-gray-700">
                    For insurance purpose only: <span className="font-normal text-gray-600">Please note that cover will revert to third party only if the vehicle is not valued within 14 days of cover inception.</span>
                </p>
            </div>
          </main>
           <footer className="text-center text-xs text-gray-400 mt-12 pt-4 border-t">
                This is a computer-generated document and does not require a signature.
            </footer>
        </div>
      </div>
    </div>
  );
}
